BT_PhanLop.Web/Controllers/EmployeeController.cs
using BT_PhanLop.Entity;
using BT_PhanLop.Models;
using BT_PhanLop.Services;
using Microsoft.AspNetCore.Mvc;

namespace BT_PhanLop.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployee _employeeService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public EmployeeController(IEmployee employeeService, IWebHostEnvironment webHostEnvironment)
        {
            _employeeService = employeeService;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            var employee = _employeeService.GetAll().Select(employee => new EmployeeIndexViewModel
            {
                Id = employee.Id,
                EmployeeNo = employee.EmployeeNo,
                FullName = employee.FullName,
                Gender = employee.Gender,
                ImageUrl = employee.ImageUrl,
                DateJoined = employee.DateJoined,
                Designation = employee.Designation,
                Email = employee.Email
            }).ToList();
            return View(employee);
        }

        public IActionResult Detail(int id)
        {
            var employee = _employeeService.GetById(id);
            if (employee == null)
            {
                return NotFound();
            }
            EmployeeDetailsViewModel model = new EmployeeDetailsViewModel()
            {
                Id = employee.Id,
                EmployeeNo = employee.EmployeeNo,
                FullName = employee.FullName,
                Gender = employee.Gender,
                ImageUrl = employee.ImageUrl,
                DoB = employee.DoB,
                Designation = employee.Designation,
                Email = employee.Email,
                NationalInsuranceNo = employee.NationalInsuranceNo,
                PaymentMethod = employee.PaymentMethod,
                StudentLoan = employee.StudentLoan,
                UnionMember = employee.UnionMember,
                Address = employee.Address,
                City = employee.City,
                PostCode = employee.PostCode
            };
            return View(model);
        }
        [HttpGet]
        public IActionResult Create()
        {
            var model = new EmployeeCreateViewModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(EmployeeCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var employee = new Employee
                {
                    Id = model.Id,
                    FirstName = model.FirstName,
                    MiddleName = model.MidleName,
                    LatName = model.LastName,
                    Gender = model.Gender,
                    DoB = model.DOB,
                    DateJoined = model.DateJoined,
                    Designation = model.Designation,
                    NationalInsuranceNo = model.NationalInsuranceNo,
                    StudentLoan = model.StudentLoan,
                    PaymentMethod = model.PaymentMethod,
                    UnionMember = model.UnionMember,
                    Phone = model.Phone,
                    Address = model.Address,
                    City = model.City,
                    PostCode = model.Postcode,
                    Email = model.Email,
                    EmployeeNo = model.EmployeeNo,
                    FullName = model.FullName
                };
                if (model.ImageUrl != null & model.ImageUrl.Length > 0)
                {
                    var uploadDir = @"images/employees";
                    var filename = Path.GetFileNameWithoutExtension(model.ImageUrl.FileName);
                    var extension = Path.GetExtension(model.ImageUrl.FileName);
                    var webrootPath = _webHostEnvironment.WebRootPath;
                    filename = DateTime.UtcNow.ToString("yymmssfff") + filename + extension;
                    var path = Path.Combine(webrootPath, uploadDir, filename);
                    await model.ImageUrl.CopyToAsync(new FileStream(path, FileMode.Create));
                    employee.ImageUrl = "/" + uploadDir + "/" + filename;

                }
                await _employeeService.CreateAsync(employee);
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var employee = _employeeService.GetById(id);
            if (employee == null)
            {
                return NotFound();
            }
            var model = new EmployeeEditViewModel()
            {
                Id = employee.Id,
                FirstName = employee.FirstName,
                LastName = employee.LatName,
                MidleName = employee.MiddleName,
                EmployeeNo = employee.EmployeeNo,
                Gender = employee.Gender,
                Email = employee.Email,
                DOB = employee.DoB,
                DateJoined = employee.DateJoined,
                Designation = employee.Designation,
                NationalInsuranceNo = employee.NationalInsuranceNo,
                PaymentMethod = employee.PaymentMethod,
                StudentLoan = employee.StudentLoan,
                UnionMember = employee.UnionMember,
                Address = employee.Address,
                City = employee.City,
                Postcode = employee.PostCode
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EmployeeEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                var employee = new Employee
                {
                    Id = model.Id,
                    FirstName = model.FirstName,
                    MiddleName = model.MidleName,
                    LatName = model.LastName,
                    Gender = model.Gender,
                    DoB = model.DOB,
                    DateJoined = model.DateJoined,
                    Designation = model.Designation,
                    NationalInsuranceNo = model.NationalInsuranceNo,
                    StudentLoan = model.StudentLoan,
                    PaymentMethod = model.PaymentMethod,
                    UnionMember = model.UnionMember,
                    Phone = model.Phone,
                    Address = model.Address,
                    City = model.City,
                    PostCode = model.Postcode,
                    Email = model.Email,
                    EmployeeNo = model.EmployeeNo,
                    FullName = model.FullName
                };
                if (model.ImageUrl != null & model.ImageUrl.Length > 0)
                {
                    var uploadDir = @"images/employees";
                    var filename = Path.GetFileNameWithoutExtension(model.ImageUrl.FileName);
                    var extension = Path.GetExtension(model.ImageUrl.FileName);
                    var webrootPath = _webHostEnvironment.WebRootPath;
                    filename = DateTime.UtcNow.ToString("yymmssfff") + filename + extension;
                    var path = Path.Combine(webrootPath, uploadDir, filename);
                    await model.ImageUrl.CopyToAsync(new FileStream(path, FileMode.Create));
                    employee.ImageUrl = "/" + uploadDir + "/" + filename;

                }
                await _employeeService.UpdateAsync(employee);
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var employee = _employeeService.GetById(id);
            if (employee == null)
            {
                return NotFound();
            }
            var model = new EmployeeDeleteViewModel
            {
                Id = employee.Id,
                FullName = employee.FullName
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(EmployeeDeleteViewModel model)
        {
            await _employeeService.Delete(model.Id);
            return RedirectToAction("Index");
        }
    }
}

BT_PhanLop.Web/Controllers/PaymentController.cs
using BT_PhanLop.Entity;
using BT_PhanLop.Models;
using BT_PhanLop.Services;
using BT_PhanLop.Services.Implement;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BT_PhanLop.Controllers
{
    public class PaymentController : Controller
    {
        private readonly IPayService _paySevices;
        private readonly IEmployee _employeeService;
        private readonly ITaxService _taxService;
        private readonly INationalInsuranceService _nationalInsuranceService;
        private decimal overtimeHrs;
        private decimal contractualEarnings;
        private decimal overtimeEarnings;
        private decimal totalEarnings;
        private decimal tax;
        private decimal unionFee;
        private decimal studentLoan;
        private decimal nationalInsurance;
        private decimal totalDeduction;

        public PaymentController(IPayService payService, IEmployee employeeService, ITaxService taxService, INationalInsuranceService nationalInsuranceService)
        {
            _paySevices = payService;
            _employeeService = employeeService;
            _taxService = taxService;
            _nationalInsuranceService = nationalInsuranceService;
        }

        public IActionResult Index()
        {
            var payRecords = _paySevices.GetAll().Select(pay => new PaymentRecordIndexViewModel
            {
                Id = pay.Id,
                EmployeeId = pay.EmployeeId,
                Employee = _employeeService.GetById(pay.EmployeeId),
                DatePay = pay.DatePay,
                MonthPay = pay.MonthPay,
                TaxYearId = pay.TaxYearId,
                TaxYear = _paySevices.GetTaxYearById(pay.TaxYearId).YearOfTax,
                TotalEarnings = pay.TotalEarnings,
                TotalDeduction = pay.EarningDeduction,
                NetPayment = pay.NetPayment,
            });
            return View(payRecords);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var employData = _employeeService.GetAll();
            var taxYearData = _paySevices.GetAllTaxYear();

            var model = new PaymentRecordCreateViewModel();
            model.EmployeeList = new List<SelectListItem>();
            model.TaxYearList = new List<SelectListItem>();

            foreach (var employee in employData)
            {
                model.EmployeeList.Add(new SelectListItem { Text = employee.FullName, Value = employee.Id.ToString() });
            }

            foreach (var taxYear in taxYearData)
            {
                model.TaxYearList.Add(new SelectListItem { Text = taxYear.YearOfTax, Value = taxYear.Id.ToString() });
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(PaymentRecordCreateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var payRecord = new PaymentRecord()
                {
                    Id = model.Id,
                    EmployeeId = model.EmployeeId,
                    Employee = _employeeService.GetById(model.EmployeeId),
                    DatePay = model.DatePay,
                    MonthPay = model.MonthPay,
                    TaxYearId = model.TaxYearId,
                    TaxYear = _paySevices.GetTaxYearById(model.TaxYearId),
                    TaxCode = model.TaxCode,
                    HourlyRate = model.HourslyRate,
                    HourWorked = model.HourlyWorked,
                    ContractualHours = model.ContractualHours,
                    OvertimeHours = overtimeHrs = _paySevices.OverTimeHours(model.HourlyWorked, model.ContractualHours),
                    ContractualEarnings = contractualEarnings = _paySevices.ContractualEarning(model.ContractualHours, model.HourlyWorked, model.HourslyRate),
                    OvertimeEarnings = overtimeEarnings = _paySevices.OvertimeEarnings(_paySevices.OvertimeRate(model.HourslyRate), overtimeHrs),
                    TotalEarnings = totalEarnings = _paySevices.TotalEarnings(overtimeEarnings, contractualEarnings),
                    Tax = tax = _taxService.TaxAmount(totalEarnings),
                    UnionFee = unionFee = _employeeService.UnionFee(model.EmployeeId),
                    NiC = nationalInsurance = _nationalInsuranceService.NIContribution(totalEarnings),
                    EarningDeduction = totalDeduction = _paySevices.TotalDeduction(tax, nationalInsurance, studentLoan, unionFee),
                    NetPayment = _paySevices.NetPay(totalEarnings, totalDeduction)
                };
                await _paySevices.CreateAsync(payRecord);
                return RedirectToAction("Index");
            }

            var employData = _employeeService.GetAll();
            var taxYearData = _paySevices.GetAllTaxYear();

            model.EmployeeList = new List<SelectListItem>();
            model.TaxYearList = new List<SelectListItem>();

            foreach (var employee in employData)
            {
                model.EmployeeList.Add(new SelectListItem { Text = employee.FullName, Value = employee.Id.ToString() });
            }

            foreach (var taxYear in taxYearData)
            {
                model.TaxYearList.Add(new SelectListItem { Text = taxYear.YearOfTax, Value = taxYear.Id.ToString() });
            }

            return View(model);
        }

        public IActionResult Detail(int id)
        {
            var paymentRecord = _paySevices.GetById(id);
            if(paymentRecord == null)
            {
                return NotFound();
            }

            var model = new PaymentRecordDetailViewModel()
            {
                Id = paymentRecord.Id,
                EmployeeId = paymentRecord.EmployeeId,
                Employee = _employeeService.GetById(paymentRecord.EmployeeId),
                DatePay = paymentRecord.DatePay,
                MonthPay = paymentRecord.MonthPay,
                TaxYearId = paymentRecord.TaxYearId,
                TaxYear = _paySevices.GetTaxYearById(paymentRecord.TaxYearId),
                TaxCode = paymentRecord.TaxCode,
                HourslyRate = paymentRecord.HourlyRate,
                HourlyWorked = paymentRecord.HourWorked,
                ContractualHours = paymentRecord.ContractualHours,
                OvertimeHours = paymentRecord.OvertimeHours,
                OvertimeRate = _paySevices.OvertimeRate(paymentRecord.HourlyRate),
                ContractualEarnings = paymentRecord.ContractualEarnings,
                OvertimeEarnings = paymentRecord.OvertimeEarnings,
                Tax = paymentRecord.Tax,
                Nic = paymentRecord.NiC,
                UnionFee = paymentRecord.UnionFee,
                SLC = paymentRecord.SLC,
                TotalEarnings = paymentRecord.TotalEarnings,
                TotalDeduction = paymentRecord.EarningDeduction,
                NetPayment = paymentRecord.NetPayment,
            };
            return View(model);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var paymentRecord = _paySevices.GetById(id);
            if (paymentRecord == null)
            {
                return NotFound();
            }
            var model = new PaymentRecordDeleteViewModel
            {
                Id = paymentRecord.Id,
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(PaymentRecordDeleteViewModel model)
        {
            await _paySevices.Delete(model.Id);
            return RedirectToAction("Index");
        }
    }
}

BT_PhanLop.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - BT_PhanLop</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/BT_PhanLop.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/css/style.css" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css" />
	<!-- Favicon -->
	<link rel="shortcut icon" type="image/x-icon" href="~/assets/img/favicon.png">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="~/assets/css/bootstrap.min.css">

	<!-- Fontawesome CSS -->
	<link rel="stylesheet" href="~/assets/css/font-awesome.min.css">

	<!-- Lineawesome CSS -->
	<link rel="stylesheet" href="~/assets/css/line-awesome.min.css">

	<!-- Chart CSS -->
	<link rel="stylesheet" href="~/assets/plugins/morris/morris.css">

	<!-- Main CSS -->
	<link rel="stylesheet" href="~/assets/css/style.css">

	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
		<script src="assets/js/html5shiv.min.js"></script>
		<script src="assets/js/respond.min.js"></script>
	<![endif]-->

</head>
<body>
	<!-- Main Wrapper -->
	<div class="main-wrapper">
		<!-- Header -->
		<div class="header">

			<!-- Header Title -->
			<div class="page-title-box">
				<h3>EMPLOYEE MANAGEMENT</h3>
			</div>
			<!-- /Header Title -->

			<a id="mobile_btn" class="mobile_btn" href="index.html#sidebar"><i class="fa fa-bars"></i></a>

			<!-- Header Menu -->
			<ul class="nav user-menu">
				<li class="nav-item dropdown has-arrow main-drop">
					<a href="index.html#" class="dropdown-toggle nav-link" data-toggle="dropdown">
						<span class="user-img">
							<img src="~/assets/img/profiles/avatar-21.jpg" alt="">
							<span class="status online"></span>
						</span>
						<span>Admin</span>
					</a>
					<div class="dropdown-menu">
						<a class="dropdown-item" href="profile.html">My Profile</a>
						<a class="dropdown-item" href="login.html">Logout</a>
					</div>
				</li>
			</ul>
			<!-- /Header Menu -->
			<!-- Mobile Menu -->
			<div class="dropdown mobile-user-menu">
				<a href="index.html#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
				<div class="dropdown-menu dropdown-menu-right">
					<a class="dropdown-item" href="profile.html">My Profile</a>
					<a class="dropdown-item" href="login.html">Logout</a>
				</div>
			</div>
			<!-- /Mobile Menu -->
		</div>
		<!-- /Header -->
		<!-- Sidebar -->
		<div class="sidebar" id="sidebar">
			<div class="sidebar-inner slimscroll">
				<div id="sidebar-menu" class="sidebar-menu">
					<ul>
						<li class="submenu">
							<a asp-controller="Employee" asp-action="Index"><i class="la la-user"></i> <span> Employees</span> <span class="menu-arrow"></span> </a>
							<ul style="display: none;">
								<li><a asp-controller="Employee" asp-action="Index"> List Employees </a></li>
								<li><a asp-controller="Employee" asp-action="Create"> Create Employee </a></li>
							</ul>
						</li>
						<li class="submenu">
							<a asp-controller="Payment" asp-action="Index"><i class="la la-money"></i> <span> Payroll </span> <span class="menu-arrow"></span> </a>
							<ul style="display: none;">
								<li><a a asp-controller="Payment" asp-action="Index"> Payment Records </a></li>
								<li><a a asp-controller="Payment" asp-action="Create"> Create Payment Record </a></li>
							</ul>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<!-- /Sidebar -->
		<!-- Page Wrapper -->
		<div class="page-wrapper">

			@RenderBody()

		</div>
		<!-- /Page Wrapper -->
	</div>
	<!-- /Main Wrapper -->


	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>

	<!-- jQuery -->
	<script src="~/assets/js/jquery-3.2.1.min.js"></script>

	<!-- Bootstrap Core JS -->
	<script src="~/assets/js/popper.min.js"></script>
	<script src="~/assets/js/bootstrap.min.js"></script>

	<!-- Slimscroll JS -->
	<script src="~/assets/js/jquery.slimscroll.min.js"></script>

	<!-- Chart JS -->
	<script src="~/assets/plugins/morris/morris.min.js"></script>
	<script src="~/assets/plugins/raphael/raphael.min.js"></script>
	<script src="~/assets/js/chart.js"></script>

	<!-- Custom JS -->
	<script src="~/assets/js/app.js"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>